SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE)
FROM USED_GOODS_USER u JOIN USED_GOODS_BOARD b ON u.USER_ID = b.WRITER_ID
WHERE b.STATUS in ('DONE')
GROUP BY u.USER_ID
HAVING SUM(b.PRICE) >= 700000
ORDER BY SUM(b.PRICE)